spoj_to_codeforces_map = {
    'euler-circuit': 'TODO',
    'inversion': 'TODO',
    'linear-algebra': 'math',
    'counting-1': 'TODO',
    'adhoc-19': 'implementation',
    'sweep': 'geometry',
    'nimbers': 'games',
    'tree-14': 'trees',
    'primality-test': 'number theory',
    'text-processing': 'expression parsing',
    'factorial': 'math',
    'inclusion-exclusion': 'TODO',
    'lcp': 'strings',
    'csg523': 'none',
    'logic': 'TODO',
    'greedy': 'greedy',
    'lds': 'TODO',
    'dp-202': 'dynamic programming',
    'rmq-4': 'TODO', # segment trees?
    'sorting': 'sortings',
    'gcd': 'math',
    'math': 'math',
    'bit-3': 'bitmasks',
    'ad-hoc-1': 'implementation',
    'bubble-cup-6-round-2': 'none',
    'fast-fourier-transofm': 'fft',
    'maths-2': 'math',
    'basic': 'implementation',
    'priority-queue': 'TODO',
    'tutorial': 'implementation',
    'geometry': 'geometry',
    'quicksort': 'sortings',
    'segment-tree-73': 'TODO', # segment
    'plane-geometry': 'geometry',
    'linear-recurrence': 'TODO',
    'nhspc2016': 'none',
    'divide-and-conquer': 'divide and conquer',
    'bubble-cup-6-round-1': 'none',
    'bubble-cup-8-round-2': 'none',
    'sub-linear': 'TODO',
    'structures': 'data structures',
    'bubble-cup-8-round-1': 'none',
    'dp-11': 'dynamic programming',
    'shortest-path': 'shortest paths',
    'binarysearch-1': 'binary search',
    'shanghai-2009': 'none',
    'bruteforce-4':' brute force',
    'dynamic-programming-72': 'dynamic programming',
    'adhoc': 'implementation',
    'big-numbers': 'math',
    'numbe': 'TODO',
    'queue': 'data structures',
    'branchandbound': 'TODO',
    'rmq-1': 'TODO', # segment
    'kruskal-s-algorithm': 'trees', # also greedy?
    'edi2016': 'none',
    'bubble-cup-10-round-2': 'none',
    'binarysearch-9': 'binary search',
    'convex-hull': 'TODO',
    'stable-marriage-problem': 'TODO',
    'segment-tree-1': 'TODO', # segment
    'bubble-cup-9-round-1': 'none',
    'suffix-array-8': 'string suffix structures',
    'tree': 'trees',
    'stack': 'data structures',
    'dfs': 'dfs and similar',
    'totient': 'number theory', #?
    'carrom' : 'TODO',
    'math-6': 'math',
    'pointers': 'two pointers',
    'bipartite-graph': 'graphs',
    'data-1': 'TODO',
    'digit-dp-1': 'dynamic programming',
    'sub-quadratic': 'TODO',
    'dynamic-programming': 'dynamic programming',
    'number-theory': 'number theory',
    'bitwise': 'bitmasks',
    'bubble-cup-9-round-2': 'none',
    'knapsack': 'dynamic programming',
    'scc': 'graphs',
    'precalculation': 'TODO',
    'dirichlet-convolution': 'TODO',
    'bitmasks': 'bitmasks',
    'lowest-common-ancestor': 'trees',
    'twopointers': 'two pointers',
    'graph-theory': 'graphs',
    'dijsktra-s-algorithm': 'shortest paths',
    'bubble-cup-7-round-2': 'none',
    'polynomial-multiplication': 'TODO', # fft?
    'string-matching': 'strings',
    'probability-theory': 'probabilities',
    'max-flow': 'flows',
    'generating-function': 'TODO',
    'polynomial': 'TODO',
    'bubble-cup-7-round-1': 'none',
    'board-game': 'games',
    'hangzhou-2008': 'none',
    'disjoint-set-2': 'dsu',
    'min-cut': 'flows',
    'recursion': 'TODO',
    'matrix': 'matrices',
    'fft-2': 'fft',
    'karatsuba': 'TODO',
    'matching': 'graph matchings',
    'linked-list-1': 'data structures',
    'sliding-window-1': 'two pointers',
    'heap': 'data structures',
    'xor-2': 'bitmasks',
    'sqrt-decomp': 'TODO',
    'lcs': 'strings', # dp?
    'data-structure-1': 'data structures',
    'stirling': 'combinatorics', #?
    'simple-math': 'math',
    'josephus-problem-1': 'TODO',
    'combinatorics': 'combinatorics',
    'simulations': 'TODO',
    'brute-force': 'brute force',
    'sieve': 'number theory',
    'binary-tree': 'trees', #?
    'goc-s01e01': 'none',
    'binary-search': 'binary search',
    'factorisation': 'number theory',
    'game-theory-1': 'games',
    'hash-table': 'data structures', #?
    'prime-numbers-1': 'number theory',
    'hashing': 'hashing',
    'backtracking': 'brute force',
    'datastructures': 'data structures',
    'newyear2017': 'none',
    'kmp-algorithm': 'strings',
    'mst': 'TODO',
    'trie-1': 'tree', #strings?
    'game': 'games',
    'cryptography': 'number theory',
    'fast-prime-factorization': 'number theory',
    'sieve-of-eratosthenes': 'number theory',
    'tree-25': 'trees',
    'dirichlet-generating-function': 'TODO',
    'graph': 'graphs',
    'z-1': 'TODO',
    'dp-10': 'dynamic programming',
    'fast-prime-counting': 'number theory',
    'numbertheory': 'number theory',
    'bfs': 'dfs and similar',
    'short-coding': 'implementation' #?
}